version: '3'

services:
  postgres:
    image: postgres
    container_name: pg_c
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data
    network_mode: bridge

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_c
    network_mode: bridge
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "3000:3000"
    container_name: frontend
    image: frontend
    command: npm start

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
     - "3001:3001"
    container_name: backend
    image: backend
    depends_on:
      - postgres
    command: npm start 



volumes:
  pg_data:
  pgadmin_data:

 