version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile 
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - postgres-server
    command: sh -c "kill-port 5001 && npm install && sleep 10 && npm start" 
  postgres-server:
    image: postgres
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: andy.huizenga@student.ehb.be
      PGADMIN_DEFAULT_PASSWORD: Huizen03ga01
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres-data: