version: '3'
services:
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development


