version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - .env
    command: npm run start-dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start

  postgres-server:
    image: postgres
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: andy.huizenga@student.ehb.be
      PGADMIN_DEFAULT_PASSWORD: Huizen03ga01
    ports:
      - "5050:80"

networks:
  app-network:
    driver: bridge

volumes:
  pgadmin-data:
  postgres-data:
